export const profileFields = [
  ['email', 'Primary email of the user'],
  ['secondary_email', 'Secondary contact email'],
  ['phone', 'Phone number'],
  ['first_name', "User's first name"],
  ['last_name', "User's last name"],
  ['locale', 'Language/locale code'],
  ['timezone', 'User timezone'],
  ['dob', 'Date of birth'],
  ['gender', 'Gender identity'],
  ['address', 'User address'],
  ['zip', 'Postal/ZIP code'],
  ['city', 'City'],
  ['state', 'State'],
  ['country', 'Country'],
  ['linkedin_url', 'LinkedIn profile URL'],
  ['job_title', 'Designation/role'],
  ['company_name', 'Company name'],
  ['company_website', 'Website URL'],
]

export const standardEvents = [
  ['application_approved', 'Application is approved by system or admin'],
  ['book_appointment', 'User books an appointment slot'],
  ['complete_registration', 'User completes account registration'],
  ['contact', 'User sends a contact or support request'],
  ['converted_lead', 'Lead successfully converted'],
  ['key_page_view', 'User views an important page'],
  ['page_view', 'User views a page'],
  ['purchase', 'User completes a purchase'],
  ['qualified_lead', 'Lead meets qualification criteria'],
  ['request_quote', 'User requests a quote or pricing'],
  ['signup', 'User creates a new account'],
  ['start_trial', 'User starts a free trial'],
  ['submit_application', 'User submits an application form'],
  ['submit_lead_form', 'User submits a lead capture form'],
  ['subscribe', 'User subscribes to a plan or newsletter'],
  ['add_to_cart', 'User adds an item to cart'],
  ['add_to_wishlist', 'User adds an item to wishlist'],
  ['checkout_started', 'User starts checkout flow'],
  ['customize_product', 'User customizes product options'],
  ['search', 'User performs a search query'],
  ['add_payment_info', 'User saves or enters payment details'],
  ['refunded', 'An order payment is refunded'],
  ['order_fullfilled', 'Order is fulfilled and processed for delivery'],
]
